### PR TITLE
VR tutorial cleanup and code refactor

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
This PR contains a number of changes I made to the project after getting it working with Godot 3.1.

Most of the changes are just code refactors that make the code a little cleaner and easier to understand. I also fixed a few bugs in the project and added some (minor) additional features.

**Changes**:

- [x] Added rumble when objects are picked up, the guns are fired, and when the sword collides with something.
- [x] Added a raycast "laser sight" to the Shotgun for easier aiming
- [x] Added a new knockback/collision-force system to the pistol, shotgun, and bomb objects. Now the closer the object is to the collision, the farther it goes.
  * This change also makes the bombs a little more consistent and natural looking.
- [x] Added some code to silence the GDScript code warnings. Nothing major was silenced, with most of the warnings being due to not using the return value from the `connect` function.
- [x] Created a base class, VR_Interactable_Rigidbody, to use for all interactable Rigidbodies in the game.
  * This makes the code a little easier and should allow for defining a consistent interface for intractable VR objects. Right now the class is rather bare, but in a future PR I might expand upon it, moving some of the object related code out of the VR controller script and into this class.
- [x] Changed the code within the VR controller to use VR_Interactable_Rigidbody instead of checking for methods.
- [x] Changed the name of the project to "Godot OpenVR FPS"
- [x] Changed the Vignette shader strength to a uniform so the strength can be changed without having to edit the shader.
- [x] Refactored the VR controller class.
  * The code has been broken down into smaller functions. The code itself didn't really change any, but by breaking it down into smaller, more compact functions, it should be easier to made adjustments in the future. Breaking everything down into smaller functions should also make writing/updating the tutorial a lot easier too.
- [x] Refactored the sword code and scene
  * Now it uses a KinematicBody for collision detection. While this may impact performance slightly, as the collision detection is done every frame, the entire thing feels WAY better and the code is simpler.
- [x] Updated all of the comments within the code. Now they are accurate and reflect the changes within this PR.
  * The comments also have better explanations and I fixed some code style inconsistencies.
- [x] Removed the glow effect from the WorldEnvironment. While it made a minor difference to the visuals, removing it should make performance a little better while also making the project more compatible with GLES2.
- [x] Fixed issue where the shotgun raycasts would send targets towards the player. Now when the shotgun fires, objects hit fly away from the end of the shotgun.
- [x] Fixed issue where the meshes used for teleportation and raycast-grabbing in the VR controller were initially visible. Now the meshes are only visible when the player starts teleporting and/or changes grab modes.

I think the list above contains most, if not all, of the changes. I made most of the initial changes late at night, so I may have missed a few. Also, some of the changes are made by Godot when opening the TSCN files.

*If there are other small additional things anyone can think of, please let me know either by commenting in this PR and/or by making a GitHub issue. I'll update this post as additional changes are made*

### CODE REVIEW

**Comment by TwistedTwigleg** [comment]
Okay! Now all that is left is updating the tutorial on the Godot documentation repository. Once that is done and this PR is merged, the VR starter tutorial is fully ready and updated for Godot 3.1. I haven't kept up as much with the development of Godot 3.2, but I think the VR tutorial should be compatible so long as nothing major has changed.

Right now I'm leaving the PR in case I bugs are found and/or I need to make minor changes as I update the tutorial.

**Comment by BastiaanOlij** [comment]
Sorry for the late reply, finally got some time to play around with this. It all works on my index for the most part :)

Understandably with the Vive you have a grab action and drop action, but with both the index knuckles and oculus touch controllers I would add an option so you need to keep the button pressed to hold an object.

I also found that I had to have my hands on an object to grab it instead of being in range. A more physical interaction but not always handy if you lack full roomscale tracking.

But looks like all your changes work fine. I need to play more and start seeing what I can tweak/improve :)

I'm going to see if I can make this work on the quest this week :)

**Comment by BastiaanOlij** [comment]
ps, I'm happy to merge this and will do separate PRs as we improve things, that way we can match the PRs with any changes in documentation.

**Comment by TwistedTwigleg** [comment]
No problem, thanks for looking through it!
As for the changes, I agree that keeping the button held for grabbing would be a good idea for controllers that have more natural grabbing buttons.

For the Windows Mixed Reality controllers, which is what I use, in my opinion having grabbing where you do not need to hold the button makes it easier. I don't know for the other VR controllers out there, but I think it would probably be best to make the default grab behavior more like a toggle, where you can change it (somehow) to be where objects are only held when the grab button is held.

As far as having to have your hands on an object to grab it, that is the default grab mode. You can change the grab mode to use a Raycast by pressing the menu button on the VR controller, which makes it easier to grab objects when you lack full roomscale tracking. That said, the Raycast is rather short, so that still might be an issue.

Thanks again for looking through it! I'll merge this PR in and when the project is good to go, I'll update the PR for the Godot documentation to reflect any changes made to the VR project.

**Pull request merged**
